### ISSUE TITLE
Roll and Pitch for Pose data

### ISSUE THREAD

**Issue by shiyingZhang90** [genforce/interfacegan#39]
Hi Shenyujun,
Thanks so much for awesome work! I saw you have pose direction in repo, but there is no roll or pitch rotation for pose in that direction. Do you think it's possible to train with both pitch, roll and yaw? BTW, any attribute predictor or data could share regarding the pose generation? That will be really helpful, not found in original stylegan repo.
Thanks

**Comment by shiyingZhang90** [comment]
And one more sad thing is when I use yaw data and roll data to train the SVM model separately, the results is same! They all look like yaw direction, any idea why?
![image](https://user-images.githubusercontent.com/53356251/76380571-60a0d100-6310-11ea-9b48-0be68782e0b6.png)
![image](https://user-images.githubusercontent.com/53356251/76380588-6c8c9300-6310-11ea-83ce-5ac707b36c79.png)

**Comment by ShenYujun** [comment]
You can definitely train three boundaries with respect to yaw, pitch, roll, respectively. However, since the training datasets, both FF-HQ and CelebA-HQ, are pre-aligned, I suspect the variations on pitch and roll dimensions are very limited.

As for the problem of the same results on yaw and roll, I guess it is the same reason as above. All synthesized faces are with a neutral pose on pitch and roll dimensions, therefore, your predictor fails to capture imperceptible changes. Instead, the predictor always uses yaw as the reference for prediction.

**Comment by shiyingZhang90** [comment]
Hi Shenyujun,
I totally agree with what you said and I'm thinking about whether there is any workaround. If training the boundary only need several hundred or several thousand, we can use face images downloaded online to get around FF-HQ and CelebA-HQ pre-aligned issue, right? I can get latents code from the image and get pose attribute from those images. Or you have better suggestion there?
I do consider if we need all pitch, roll and yaw in pose for controlling latent vector, will non-linear model suits better than current linear regression? Have you thought of having attribute boundary with three or more dimension? Will that be hard to optimize and get good results? Worst case, we can train pitch, yaw, roll separately and modify it one at a time I guess

**Comment by shiyingZhang90** [comment]
Well, one issue I discovered when I tried my method above is I don't find a way to generate qlatents in z space for image to latents transform, all available online is to dlatents in wp space. Any idea there?

**Comment by ShenYujun** [comment]
For high-dimension subspace manipulation, we are working on it right now, so I may not be able to talk more about that. For training boundaries in W+ space, please refer to [issue 38](https://github.com/genforce/interfacegan/issues/38). For GAN inversion to Z space, to my best knowledge, all existing methods show poor results. One possible reason is that the dimension of Z is too low to represent high-quality faces. However, our [multi-code GAN prior](https://arxiv.org/pdf/1912.07116.pdf) may provide an alternative solution. The code will be released soon.

**Comment by WengRan** [comment]
Hello, I faced the same problem , May I ask if you have resolved it  .  If yes, could you share your pitch direction with me?
Thank you !!!
