### ISSUE TITLE
Can it make an adult into a baby？

### ISSUE THREAD

**Issue by WJ-Lai** [genforce/interfacegan#40]
Hi, the age demo in the paper makes an adult into a  child, could you please tell me what will if I set the age attribute as an extreme value?

Can it make an adult into a one-year-old baby？Can it keep the generator output a normal human face?

**Comment by ShenYujun** [comment]
Yes, the model trained on FF-HQ dataset is able to achieve this goal since FF-HQ dataset is highly diverse with respect to age. Just keep moving the latent code along the negative age direction.

**Comment by WJ-Lai** [comment]
> Yes, the model trained on FF-HQ dataset is able to achieve this goal since FF-HQ dataset is highly diverse with respect to age. Just keep moving the latent code along the negative age direction.

Thanks for your replay! Could you please tell me what environment should I install for this code? Is it the same as StylenGAN?(TensorFlow 1.10.0 or newer?)

**Comment by ShenYujun** [comment]
The environment is listed on the top of README. Yes, you will need tensorflow ONLY for model conversion.

**Comment by WJ-Lai** [comment]
> The environment is listed on the top of README. Yes, you will need tensorflow ONLY for model conversion.

Thanks for your replay! I'm still confused about how can I get the latent code for my own image.

In issue38(https://github.com/genforce/interfacegan/issues/38) saying that after using the stylegan-encoder project, it still needs some process to deal with the output latent code.

Can you please write down which is the easiest way to get the latent code? 
Is there some code in your project that I can output latent code for my own image directly?

**Comment by ShenYujun** [comment]
Current codebase does not supply inverting an image to a latent code. But we are planning on another work which focuses on GAN inversion. If you are interested, you can follow https://genforce.github.io/. That work will be released in 1-2 weeks.

**Comment by WJ-Lai** [comment]
Thank you. Looking forward to your work.
