### ISSUE TITLE
Issue with tensorflow version

### ISSUE THREAD

**Issue by nandhini673** [genforce/interfacegan#41]
When I try to install tensorflow 1.12.2 as I believe tensorflow 1.12.2 and cudo 9 are compatible to execute this code.. I'm getting version mismatch error and some other version of gets installed and when try to display tensorflow version I'm getting errors... images are not getting for other versions of tensorflow generated..

**Comment by ShenYujun** [comment]
About how to install tensorflow properly, please refer to [the official repo](https://github.com/tensorflow/tensorflow).
