### ISSUE TITLE
How to manipulate real faces?

### ISSUE THREAD

**Issue by AddASecond** [genforce/interfacegan#44]
Dear author, after checking this repository, I have found that there isn't included a encoder-decoder model as the paper tests in Figure 11. WILL this release in the near future?

**Comment by ShenYujun** [comment]
Please refer to [this repo](https://github.com/zhujiapeng/LIA).

**Comment by ltnghia** [comment]
Hello, I use LIA to extract latent codes from input images and then use them as inputs for interfacegan. However, I cannot generate results of the same input images of LIA. Do I need to process extracted latent codes?
`
E, _, _, Gs, _ = load_pkl(args.restore_path)
real = tf.placeholder('float32', [None, 3, args.image_size, args.image_size], name='real_image')
encoder_w = E.get_output_for(real, phase=False)
sess = tf.get_default_session()
latent_code = sess.run(encoder_w, feed_dict={real: input_image})
np.save('%s/%s.npy' % (save_dir, im_name), latent_code)
`
`
python edit.py \
    -m pggan_celebahq \
    -b boundaries/pggan_celebahq_smile_boundary.npy \
    -i $INPUT_LATENT_CODES_PATH \
    -o results/from_latent_code/pggan/celebahq/smile_editing

python edit.py \
    -m stylegan_ffhq \
    -b boundaries/stylegan_ffhq_smile_boundary.npy \
    -i $INPUT_LATENT_CODES_PATH \
    -o results/from_latent_code/stylegan/ffhq/smile_editing
`

**Comment by ShenYujun** [comment]
You are using the official PGGAN (pggan_celebahq) and StyleGAN (stylegan_ffhq) models for editing, but LIA uses its own model for inversion. Please find the boundaries for LIA model and use them for manipulation. This repo only contains the boundaries and editing script w.r.t. PGGAN and StyleGAN.

**Comment by ltnghia** [comment]
Can you give a guidance to reproduce results in Fig.11? Thank you.

**Comment by ShenYujun** [comment]
1. Find your own boundaries with LIA model (this process is exactly the same as that of PGGAN and StyleGAN).
2. Invert real images with LIA encoder and get the inverted codes.
3. Move the inverted codes towards the boundaries (use `utils/manipulator.py`)
4. Use the LIA generator to produce images with the manipulated codes.
