### ISSUE TITLE
Trying to use a pretrained stylegan with gray-scaled images 

### ISSUE THREAD

**Issue by yilmazkorkmz** [genforce/interfacegan#45]
Hi,

I am trying to use generate_data.py with a trained stylegan on gray-scaled images, i registered my model in model_settings.py and specified number of channels as 1 in there. However, it turns out that something in the original model is fixed size to 3, the error is:

RuntimeError: Error(s) in loading state_dict for StyleGANGeneratorModel:
	size mismatch for synthesis.output6.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([3]).

Do you have any idea, how can i solve this. 

Thanks in advance.

**Comment by ShenYujun** [comment]
Please change `3` to `out_channels` on [Line 757](https://github.com/genforce/interfacegan/blob/c265126e1dba10e9dc2f17c5e24ac7ce2edf24c6/models/stylegan_generator_model.py#L757) of `models/stylegan_generator_model.py`. Or you can use the latest version in [HiGAN](https://github.com/genforce/higan). Good luck.

**Comment by yilmazkorkmz** [comment]
it solved the problem, thanks.
