### ISSUE TITLE
Regarding yaw pose estimation using facial landmarks

### ISSUE THREAD

**Issue by parthpatel002** [genforce/interfacegan#46]
Hi, 

I wish to apply your technique to a StyleGAN model that I have trained on Celeba-HQ-128 images. Can you please release the code to estimate yaw pose using the five facial landmarks present in CelebA dataset (left eye centre, right eye centre, nose tip, left mouth corner and right mouth corner)?  

Thanks.

**Comment by ShenYujun** [comment]
We currently do not have plans on releasing the facial landmark predictor. However, you can use [this script](https://github.com/Puzer/stylegan-encoder/blob/master/ffhq_dataset/landmarks_detector.py) instead. Good luck.
