### ISSUE TITLE
Attribute Scores

### ISSUE THREAD

**Issue by Agrechka** [genforce/interfacegan#48]
Hello, thanks for the great work. 
I would like to know if it is possible to see the code for the attribute predictor you used, or if you could share the scores of these directly to be able to find boundaries on different architectures but with the same dataset. 
Thanks very much

**Comment by ShenYujun** [comment]
Thanks for liking our work. We will release the facial attribute predictors in the future ;)

**Comment by krishnamecho** [comment]
@ShenYujun 
It would be quite helpful if you release the attribute predictor. Did you release the predictor?
