### ISSUE TITLE
Tencent wrote a patent ，using the same way in your paper

### ISSUE THREAD

**Issue by xiaohaipeng** [genforce/interfacegan#49]
[中国发明] CN202010341415.0 人脸图像编辑方法、装置和存储介质
![image](https://user-images.githubusercontent.com/30681655/87047683-66121780-c22d-11ea-9e49-5b15222d5973.png)
bitch tencent

**Comment by ShenYujun** [comment]
Oh my god! Thanks for pointing this out.

**Comment by xuyanging** [comment]
小心南山必胜客告你.....

**Comment by visbox** [comment]
Run into this repo: https://github.com/SummitKwan/transparent_latent_gan . It seems to share the same idea.
