### ISSUE TITLE
Latent code- attribute score pair

### ISSUE THREAD

**Issue by krishnamecho** [genforce/interfacegan#53]
What are the latent code-attribute score as mentioned in the train_boundary.py file in the repository? How can we calculate the attribute scores?

**Comment by miss1997yuan** [comment]
add one

**Comment by ShenYujun** [comment]
Use a pre-trained attribute classifier. We may provide some classifiers in the future. You can also train your own classifiers.

**Comment by krishnamecho** [comment]
Yeah, Can you provide those classifiers shortly or direct us the way to generate customized classifiers ? 
It would be a great help.

**Comment by RioRic** [comment]
When you can share the per-tained attribute classier or code  to generate the classifier

**Comment by yoichi1484** [comment]
Can you mind telling me what dataset you used for the attribute classifier?

**Comment by ShenYujun** [comment]
It is the CelebA data that we use. You can find the link [here](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html).

**Comment by yoichi1484** [comment]
> It is the CelebA data that we use. You can find the link [here](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html).

Thank you!

**Comment by liujingwen-bmil** [comment]
> Yeah, Can you provide those classifiers shortly or direct us the way to generate customized classifiers ? It would be a great help.

hello, have you already known how to generated customized classifiers? Any help would be appreciated!

**Comment by YKJamesMoriarty** [comment]
潜在空间就是stylegan生成器的输入，这个输入是从高维正态分布中取值的一个向量X。然后用这个向量X作为输入在已经训练好的stylegan中推理生成一张图片，接着将这张图片送入一个与训练好的某些人像特征的分类器（如年龄、微笑程度、是否带了眼镜），得到这张图片中这几个特征的分数，最后将生成这种图片的向量X与得到的分数作为一对信息，传入SVM中做语义边界划分
