### ISSUE TITLE
How to get the corresponding age datasets?

### ISSUE THREAD

**Issue by berylsheep-up** [genforce/interfacegan#54]
Hello, thanks for the excellent work!
The paper said the attribute assessor are trained on the celebA datasets. When I look through the celebA[http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html](url), i only can find the young label which is related to the age attribute. But it seems that the assessors are trained on binary datasets ( old vs. young). Can you explain more about the age datasets? Thanks a lot!

**Comment by ShenYujun** [comment]
Young is a binary attribute in CelebA, where 1 means young and 0 means old.
