### ISSUE TITLE
Question from the Fig.9 of the paper

### ISSUE THREAD

**Issue by ChengBinJin** [genforce/interfacegan#56]
@zhoubolei @ShenYujun
Hi, thanks for your excellent work. 
According to the row-3 "Z space w/ Condition" of Figure 9 in your paper, the conditional manipulation based on the Z space (StyleGAN) is better than W space?

**Comment by ShenYujun** [comment]
Yes, you are right. Please find the explanation in Sec.3.4. You can also find more details in the [extended version](https://arxiv.org/pdf/2005.09635.pdf).

**Comment by ChengBinJin** [comment]
@ShenYujun 
Thank you very much! The template of this paper looks like PAMI. Hope to hear good news.
