### ISSUE TITLE
Is there a way to only change the smiling expression while keep other facial attributes unchanged?

### ISSUE THREAD

**Issue by Melody-doudou** [genforce/interfacegan#60]
Thanks for sharing the code! I used pretrained pggan_celebahq_smile_boundary.npy to generate images with neutral expression and smiling expression. However other attributes change, such as skin color or gender. Is there a way to only change the smiling expression while keep other facial attributes unchanged? Thanks.

**Comment by ShenYujun** [comment]
Keeping all other attributes remained is extremely challenging. But you can easily keep one attribute preserved with the proposed conditional manipulation. For more details, please refer to the [paper](https://arxiv.org/pdf/2005.09635.pdf).

**Comment by Melody-doudou** [comment]
> Keeping all other attributes remained is extremely challenging. But you can easily keep one attribute preserved with the proposed conditional manipulation. For more details, please refer to the [paper](https://arxiv.org/pdf/2005.09635.pdf).

I see, thank you!
