### ISSUE TITLE
Can this work be used for video generation?

### ISSUE THREAD

**Issue by kaiqiangh** [genforce/interfacegan#65]
Thanks for sharing your codes and work.

I would ask: Can this work be used to generate video samples according to the related objects? For example, an action class is called "go skateboarding". This action could have some objects such as skateboard, snow and so on. Can we manipulate random noise Z by replacing with object representations to make the generated video samples much closer (more similar) to the "go skateboarding" class looks like? 

Thanks.

**Comment by ShenYujun** [comment]
I'm sorry but I am not sure I fully understand your question.

**Comment by kaiqiangh** [comment]
Thanks for your reply.

Let me be clear. I try to generate video instances conditioned on the class label via conditional GAN (e.g. generating video instances for the class of "go skateboarding"). According to your work, it seems like you can edit/change somewhere in random noise as input for training generator. For a simple question, Can this work be used to generate video samples by manipulating random noise in some ways (input both manipulated random noise and class label together to generator)?

Thanks!

**Comment by ShenYujun** [comment]
I think it is possible.

**Comment by kaiqiangh** [comment]
Thanks. I will try it.
