### ISSUE TITLE
hyperplane crosses origin

### ISSUE THREAD

**Issue by ziqihuangg** [genforce/interfacegan#67]
Dear authors, thanks for your excellent work!

May I ask whether you assumed that the hyperplane in the latent space always contains the origin? If so, what might be the reasons for this assumption? Is it possible to better linearly separate the semantics in latent space by a hyperplane that doesn't necessarily cross the origin? That is, to add a bias term when defining the latent space SVM.
(In the paper, the "distance" from a sample latent code z to a hyperplane is defined as the dot product of z and normal vector. You didn't minus the distance from the hyperplane to the origin, that's why I have this question. The SVM you use is `clf = svm.SVC(kernel='linear')`, I didn't find the sklearn documentation on whether it has a bias term.)

Thank you very much!

**Comment by ShenYujun** [comment]
Thanks for this detailed question. In real cases, the bias term does not affect that much according to our observation. You will see that even not setting bias as zero, the learned bias is small. We have clarified this issue in the latest journal [paper](https://arxiv.org/pdf/2005.09635.pdf). Please refer to the last paragraph of Sec. 3.3 on Page 4.

**Comment by ziqihuangg** [comment]
Thank you for the reply!
