### ISSUE TITLE
interfacegan generated images dataset

### ISSUE THREAD

**Issue by ofir-dl** [genforce/interfacegan#68]
Hi, 

I would like to create a dataset of images generated with interfacegan method.
This dataset should be as varied as possible (i.e age, gender, pose, etc combinations)

I can use your code to generate the images myself but before doing it I was wondering if such a dataset already exists?

Thanks!

**Comment by ShenYujun** [comment]
Please refer to [this repo](https://github.com/evgenykashin/stylegan2-distillation).
