### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by alan-ai-learner** [genforce/interfacegan#69]
hey, @ShenYujun I've got a question that In my use case I need to add sunglasses to the face or consider any type of facial attribute. So as you said earlier that "PGGAN is trained on CelebA-HQ dataset, which lacks samples wearing eyeglasses. Hence, the boundary may not be that accurate. In other words, PGGAN is not very good at generating data with eyeglasses. Meanwhile, "eyeglasses" entangle with "gender" and "age". That is why you saw the gender (together with age) changes."
Q 1. How can I generate accurate boundaries for any specific task?
Q 2. What and where should I made the changes in the code?
I need some suggestion!
Thanks

_Originally posted by @alan-ai-learner in https://github.com/genforce/interfacegan/issues/59#issuecomment-774045701_

**Comment by ShenYujun** [comment]
Please refer to the comment [here](https://github.com/genforce/interfacegan/issues/59#issuecomment-774067070).
