### ISSUE TITLE
Code for inversion of generated images.

### ISSUE THREAD

**Issue by ArthurConmy** [genforce/interfacegan#76]
I was particularly impressed by the inversion of images back to latent codes on figure 10, page 8 of https://arxiv.org/pdf/1907.10786.pdf . 

Is the code for this inversion in the repository, or available elsewhere? I was not able to find it.

**Comment by ShenYujun** [comment]
Please refer to [this repo](https://github.com/genforce/idinvert) or its [pytorch version](https://github.com/genforce/idinvert_pytorch).
