### ISSUE TITLE
Train Boundary on GPUs

### ISSUE THREAD

**Issue by GloryyrolG** [genforce/interfacegan#81]
Hi Yujun,

Thanks for the good work and code repo. May I ask how can linear SVM in `train_boundary()` be run on GPUs? Pls see
https://github.com/genforce/interfacegan/blob/acec139909fb9aad41fbdbbbde651dfc0b7b3a17/utils/manipulator.py#L119

Regards,

**Comment by ShenYujun** [comment]
I am sorry, but I really have no idea on this question. Maybe you can check `sklearn` team.
