### ISSUE TITLE
How to train a classifier to get attribute scores

### ISSUE THREAD

**Issue by UdonDa** [genforce/interfacegan#97]
Hi,
I trained resnet18 using a celeba dataset with a multi-label setting.
And, I used it to find boundaries.

However, my results show that the generated images have an entangled boundary.
The image used an only 'makeup' class.
From left to right, the scalar weight of boundary is increased.

So, I guess that the training strategy of the classifier is different from your paper.
Would you provide the detail how to train a classifier?
Thanks.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/25411643/167610063-cf225cab-7e1f-4e47-b941-6fc0442dd190.png">

**Comment by UdonDa** [comment]
Oh, I miss your conditional manipulation method...

**Comment by AMEERAZAM08** [comment]
can you send your repo link please ... ?
